name: "Gemini Agent"
version: "1.0.5"
slug: "gemini_agent"
description: "AI Agent for Home Assistant"
url: "https://github.com/nikomaxos/ha-addons"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: manual
map:
  - "config:rw"
options:
  gemini_api_key: ""
  prompt_entity: "input_text.gemini_prompt"
schema:
  gemini_api_key: str
  prompt_entity: str
homeassistant_api: true